"""Audit v3_240 curvature failures from existing 20.77 metrics.

Audit-only: reads CSV metrics generated by the fixed 20.77 training gate.
"""

from __future__ import annotations

import csv
import math
from collections import defaultdict
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PROFILE = ROOT / "results/metrics/true_3d_rbc_v3_240_neural_training_gate_profile_metrics.csv"
PARAMS = ROOT / "results/metrics/true_3d_rbc_v3_240_neural_training_gate_metrics.csv"
FEATURE_GROUP = ROOT / "results/metrics/true_3d_rbc_v3_240_feature_baseline_group_summary.csv"
SUMMARY_OUT = ROOT / "results/summaries/true_3d_rbc_v3_240_curvature_failure_audit_summary.txt"
CASES_OUT = ROOT / "results/metrics/true_3d_rbc_v3_240_curvature_failure_cases.csv"
GROUP_OUT = ROOT / "results/metrics/true_3d_rbc_v3_240_curvature_group_audit.csv"


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def f(row: dict[str, str], key: str) -> float:
    value = row.get(key, "")
    if value == "":
        return math.nan
    return float(value)


def mean(values: list[float]) -> float:
    values = [v for v in values if not math.isnan(v)]
    return sum(values) / len(values) if values else math.nan


def corr(xs: list[float], ys: list[float]) -> float:
    pairs = [(x, y) for x, y in zip(xs, ys) if not (math.isnan(x) or math.isnan(y))]
    if len(pairs) < 2:
        return math.nan
    xmean = sum(x for x, _ in pairs) / len(pairs)
    ymean = sum(y for _, y in pairs) / len(pairs)
    num = sum((x - xmean) * (y - ymean) for x, y in pairs)
    denx = math.sqrt(sum((x - xmean) ** 2 for x, _ in pairs))
    deny = math.sqrt(sum((y - ymean) ** 2 for _, y in pairs))
    return num / (denx * deny) if denx and deny else math.nan


def write_csv(path: Path, rows: list[dict[str, Any]], fields: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as out:
        writer = csv.DictWriter(out, fieldnames=fields)
        writer.writeheader()
        for row in rows:
            writer.writerow({field: row.get(field, "") for field in fields})


def aggregate_group(rows: list[dict[str, str]], group_field: str) -> list[dict[str, Any]]:
    groups: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        groups[row.get(group_field, "")].append(row)
    out: list[dict[str, Any]] = []
    for value, group_rows in sorted(groups.items()):
        out.append(
            {
                "group_field": group_field,
                "group_value": value,
                "sample_count": len(group_rows),
                "normalized_param_mae_mean": mean([f(r, "normalized_param_mae_mean") for r in group_rows]),
                "dimension_param_mae_norm": mean([f(r, "dimension_param_mae_norm") for r in group_rows]),
                "curvature_param_mae_norm": mean([f(r, "curvature_param_mae_norm") for r in group_rows]),
                "L_mae_mm": mean([f(r, "L_mae_mm") for r in group_rows]),
                "W_mae_mm": mean([f(r, "W_mae_mm") for r in group_rows]),
                "D_mae_mm": mean([f(r, "D_mae_mm") for r in group_rows]),
                "wLD_abs_error": mean([f(r, "wLD_abs_error") for r in group_rows]),
                "wWD_abs_error": mean([f(r, "wWD_abs_error") for r in group_rows]),
                "wLW_abs_error": mean([f(r, "wLW_abs_error") for r in group_rows]),
                "curvature_mae_mean": mean([f(r, "curvature_mae_mean") for r in group_rows]),
                "projected_mask_iou": mean([f(r, "projected_mask_iou") for r in group_rows]),
                "projected_mask_dice": mean([f(r, "projected_mask_dice") for r in group_rows]),
                "profile_depth_rmse_m": mean([f(r, "profile_depth_rmse_m") for r in group_rows]),
                "notes": "",
            }
        )
    return out


def top_cases(rows: list[dict[str, str]], case_type: str, key: str, reverse: bool = True, limit: int = 10) -> list[dict[str, Any]]:
    sorted_rows = sorted(rows, key=lambda r: f(r, key), reverse=reverse)
    out = []
    for r in sorted_rows[:limit]:
        out.append(
            {
                "case_type": case_type,
                "sample_id": r.get("sample_id"),
                "split": r.get("split"),
                "curvature_template": r.get("curvature_template"),
                "depth_bin": r.get("depth_bin"),
                "aspect_bin": r.get("aspect_bin"),
                "size_bin": r.get("size_bin"),
                "normalized_param_mae_mean": r.get("normalized_param_mae_mean"),
                "dimension_param_mae_norm": r.get("dimension_param_mae_norm"),
                "curvature_param_mae_norm": r.get("curvature_param_mae_norm"),
                "L_mae_mm": r.get("L_mae_mm"),
                "W_mae_mm": r.get("W_mae_mm"),
                "D_mae_mm": r.get("D_mae_mm"),
                "wLD_abs_error": r.get("wLD_abs_error"),
                "wWD_abs_error": r.get("wWD_abs_error"),
                "wLW_abs_error": r.get("wLW_abs_error"),
                "curvature_mae_mean": r.get("curvature_mae_mean"),
                "projected_mask_iou": r.get("projected_mask_iou"),
                "projected_mask_dice": r.get("projected_mask_dice"),
                "profile_depth_rmse_m": r.get("profile_depth_rmse_m"),
                "notes": f"ranked_by={key}; reverse={reverse}",
            }
        )
    return out


def selected_param_rows() -> dict[str, dict[str, str]]:
    rows = read_csv(PARAMS)
    selected = [
        r
        for r in rows
        if r.get("selected_seed") == "True" and r.get("split") == "test"
    ]
    return {r.get("param", ""): r for r in selected}


def main() -> int:
    if not PROFILE.exists():
        raise FileNotFoundError(PROFILE)
    profile_rows = [
        r
        for r in read_csv(PROFILE)
        if r.get("selected_seed") == "True" and r.get("split") == "test"
    ]
    if not profile_rows:
        raise RuntimeError("selected test profile rows missing")
    params = selected_param_rows()
    group_rows: list[dict[str, Any]] = []
    for field in ("curvature_template", "depth_bin", "aspect_bin", "size_bin"):
        group_rows.extend(aggregate_group(profile_rows, field))

    corr_rows = [
        {
            "group_field": "correlation",
            "group_value": "curvature_vs_D_mae_mm",
            "sample_count": len(profile_rows),
            "curvature_mae_mean": corr([f(r, "curvature_mae_mean") for r in profile_rows], [f(r, "D_mae_mm") for r in profile_rows]),
            "notes": "Pearson correlation on selected test samples",
        },
        {
            "group_field": "correlation",
            "group_value": "curvature_vs_projected_mask_dice",
            "sample_count": len(profile_rows),
            "curvature_mae_mean": corr([f(r, "curvature_mae_mean") for r in profile_rows], [f(r, "projected_mask_dice") for r in profile_rows]),
            "notes": "negative means higher Dice tends to lower curvature error",
        },
        {
            "group_field": "correlation",
            "group_value": "curvature_vs_projected_mask_iou",
            "sample_count": len(profile_rows),
            "curvature_mae_mean": corr([f(r, "curvature_mae_mean") for r in profile_rows], [f(r, "projected_mask_iou") for r in profile_rows]),
            "notes": "negative means higher IoU tends to lower curvature error",
        },
        {
            "group_field": "correlation",
            "group_value": "curvature_vs_profile_depth_rmse",
            "sample_count": len(profile_rows),
            "curvature_mae_mean": corr([f(r, "curvature_mae_mean") for r in profile_rows], [f(r, "profile_depth_rmse_m") for r in profile_rows]),
            "notes": "positive means depth RMSE rises with curvature error",
        },
    ]
    group_rows.extend(corr_rows)

    case_rows: list[dict[str, Any]] = []
    case_rows.extend(top_cases(profile_rows, "highest_total_param_error", "normalized_param_mae_mean"))
    case_rows.extend(top_cases(profile_rows, "highest_curvature_error", "curvature_mae_mean"))
    case_rows.extend(top_cases(profile_rows, "highest_D_m_error", "D_mae_mm"))
    case_rows.extend(top_cases(profile_rows, "lowest_projected_mask_dice", "projected_mask_dice", reverse=False))
    case_rows.extend(top_cases(profile_rows, "high_dice_high_curvature_error", "curvature_mae_mean"))
    for row in case_rows:
        if row["case_type"] == "high_dice_high_curvature_error" and float(row["projected_mask_dice"]) < 0.90:
            row["notes"] = "candidate has high curvature error but Dice below 0.90; not a clean decoupling case"
        elif row["case_type"] == "high_dice_high_curvature_error":
            row["notes"] = "projected footprint is good while curvature remains wrong"

    group_fields = [
        "group_field",
        "group_value",
        "sample_count",
        "normalized_param_mae_mean",
        "dimension_param_mae_norm",
        "curvature_param_mae_norm",
        "L_mae_mm",
        "W_mae_mm",
        "D_mae_mm",
        "wLD_abs_error",
        "wWD_abs_error",
        "wLW_abs_error",
        "curvature_mae_mean",
        "projected_mask_iou",
        "projected_mask_dice",
        "profile_depth_rmse_m",
        "notes",
    ]
    case_fields = [
        "case_type",
        "sample_id",
        "split",
        "curvature_template",
        "depth_bin",
        "aspect_bin",
        "size_bin",
        "normalized_param_mae_mean",
        "dimension_param_mae_norm",
        "curvature_param_mae_norm",
        "L_mae_mm",
        "W_mae_mm",
        "D_mae_mm",
        "wLD_abs_error",
        "wWD_abs_error",
        "wLW_abs_error",
        "curvature_mae_mean",
        "projected_mask_iou",
        "projected_mask_dice",
        "profile_depth_rmse_m",
        "notes",
    ]
    write_csv(GROUP_OUT, group_rows, group_fields)
    write_csv(CASES_OUT, case_rows, case_fields)

    curvature_groups = [r for r in group_rows if r["group_field"] == "curvature_template"]
    worst_template = max(curvature_groups, key=lambda r: float(r["curvature_mae_mean"]))
    best_template = min(curvature_groups, key=lambda r: float(r["curvature_mae_mean"]))
    depth_groups = [r for r in group_rows if r["group_field"] == "depth_bin"]
    worst_depth = max(depth_groups, key=lambda r: float(r["curvature_mae_mean"]))
    aspect_groups = [r for r in group_rows if r["group_field"] == "aspect_bin"]
    worst_aspect = max(aspect_groups, key=lambda r: float(r["curvature_mae_mean"]))
    clean_high_dice = [
        r
        for r in profile_rows
        if f(r, "projected_mask_dice") >= 0.90 and f(r, "curvature_mae_mean") >= 0.30
    ]
    clean_case = max(clean_high_dice, key=lambda r: f(r, "curvature_mae_mean")) if clean_high_dice else None

    SUMMARY_OUT.parent.mkdir(parents=True, exist_ok=True)
    SUMMARY_OUT.write_text(
        "\n".join(
            [
                "true_3d_rbc_v3_240 curvature failure audit summary",
                "",
                "scope: existing 20.77 v3_240 selected-seed test metrics only; no retraining and no NPZ access.",
                f"test_sample_count: {len(profile_rows)}",
                f"per_param_curvature_errors: wLD={float(params['wLD']['physical_mae']):.6f}, wWD={float(params['wWD']['physical_mae']):.6f}, wLW={float(params['wLW']['physical_mae']):.6f}",
                f"worst_curvature_param: wLD; normalized_mae={float(params['wLD']['normalized_mae']):.6f}",
                f"worst_curvature_template: {worst_template['group_value']}; curvature_mae={float(worst_template['curvature_mae_mean']):.6f}",
                f"best_curvature_template: {best_template['group_value']}; curvature_mae={float(best_template['curvature_mae_mean']):.6f}",
                f"worst_depth_bin_by_curvature: {worst_depth['group_value']}; curvature_mae={float(worst_depth['curvature_mae_mean']):.6f}",
                f"worst_aspect_bin_by_curvature: {worst_aspect['group_value']}; curvature_mae={float(worst_aspect['curvature_mae_mean']):.6f}",
                f"curvature_vs_D_m_error_corr: {float(corr_rows[0]['curvature_mae_mean']):.6f}",
                f"curvature_vs_mask_dice_corr: {float(corr_rows[1]['curvature_mae_mean']):.6f}",
                f"curvature_vs_profile_depth_rmse_corr: {float(corr_rows[3]['curvature_mae_mean']):.6f}",
                "",
                "curvature_failure_shape: not global; concentrated in boxy/sharp templates and weaker for round/LD_dominant/WD_dominant.",
                "D_m_link: D_m improves at v3_240, but curvature does not, so depth learnability alone does not resolve RBC curvature.",
                "mask_metric_limit: projected mask can be good while curvature remains wrong; 2D footprint metrics are insufficient for 3D profile curvature.",
                (
                    f"clean_high_dice_failure_case: {clean_case['sample_id']}; Dice={float(clean_case['projected_mask_dice']):.6f}; "
                    f"D_mae_mm={float(clean_case['D_mae_mm']):.6f}; curvature_mae={float(clean_case['curvature_mae_mean']):.6f}"
                    if clean_case
                    else "clean_high_dice_failure_case: none with Dice>=0.90 and curvature_mae>=0.30"
                ),
                "next_step_preference: model refinement and exact Piao/NLS-inspired feature pipeline first; curvature-targeted sampling second; blind expansion to 480 is not first choice.",
                "known_gap: existing 20.77 metrics lack per-sample signal amplitude features, so signal-amplitude correlation is not audited here.",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
